# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["xhci_pci" "ahci" "nvme" "usb_storage" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = [];
  boot.extraModulePackages = [];

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/743A-C3CC";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  fileSystems."/" = {
    device = "/dev/disk/by-uuid/0092d631-b490-43ea-815e-db6d41654285";
    fsType = "btrfs";
    options = ["subvol=root" "compress=zstd" "noatime" "discard=async"];
  };

  fileSystems."/home" = {
    device = "/dev/disk/by-uuid/0092d631-b490-43ea-815e-db6d41654285";
    fsType = "btrfs";
    options = ["subvol=home" "compress=zstd" "noatime" "discard=async"];
  };

  fileSystems."/nix" = {
    device = "/dev/disk/by-uuid/0092d631-b490-43ea-815e-db6d41654285";
    fsType = "btrfs";
    options = ["subvol=nix" "compress=zstd" "noatime" "discard=async"];
  };

  fileSystems."/persist" = {
    device = "/dev/disk/by-uuid/0092d631-b490-43ea-815e-db6d41654285";
    fsType = "btrfs";
    options = ["subvol=persist" "compress=zstd" "noatime" "discard=async"];
    neededForBoot = true;
  };

  fileSystems."/storage/internal" = {
    device = "/dev/disk/by-uuid/e0f7c7a3-6bfd-4a4a-8ec2-355a25e3419c";
    fsType = "btrfs";
    options = ["subvol=internal" "compress=zstd" "noatime"];
  };

  fileSystems."/storage/shared" = {
    device = "/dev/disk/by-uuid/e0f7c7a3-6bfd-4a4a-8ec2-355a25e3419c";
    fsType = "btrfs";
    options = ["subvol=shared" "compress=zstd" "noatime"];
  };

  fileSystems."/storage/nvr" = {
    device = "/dev/disk/by-uuid/e0f7c7a3-6bfd-4a4a-8ec2-355a25e3419c";
    fsType = "btrfs";
    options = ["subvol=nvr" "compress=zstd" "noatime"];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.intel.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
