# Do not modify this file!  It was generated by ‘nixos-generate-config’
# and may be overwritten by future invocations.  Please make changes
# to /etc/nixos/configuration.nix instead.
{
  config,
  lib,
  pkgs,
  modulesPath,
  ...
}: {
  imports = [
    (modulesPath + "/installer/scan/not-detected.nix")
  ];

  boot.initrd.availableKernelModules = ["nvme" "xhci_pci" "ahci" "usb_storage" "usbhid" "sd_mod"];
  boot.initrd.kernelModules = [];
  boot.kernelModules = ["kvm-amd"];
  boot.extraModulePackages = [];

  fileSystems."/" = {
    device = "/dev/mapper/crypt";
    fsType = "btrfs";
    options = ["subvol=root" "compress=zstd" "noatime" "discard=async"];
  };

  boot.initrd.luks.devices."crypt" = {
    device = "/dev/disk/by-uuid/db811b5a-b06f-4522-90fc-68a6964a9e78";
    allowDiscards = true;
  };

  fileSystems."/home" = {
    device = "/dev/mapper/crypt";
    fsType = "btrfs";
    options = ["subvol=home" "compress=zstd" "noatime" "discard=async"];
  };

  fileSystems."/nix" = {
    device = "/dev/mapper/crypt";
    fsType = "btrfs";
    options = ["subvol=nix" "compress=zstd" "noatime" "discard=async"];
  };

  fileSystems."/persist" = {
    device = "/dev/mapper/crypt";
    fsType = "btrfs";
    options = ["subvol=persist" "compress=zstd" "noatime" "discard=async"];
    neededForBoot = true;
  };

  fileSystems."/boot" = {
    device = "/dev/disk/by-uuid/2646-4AE6";
    fsType = "vfat";
    options = ["fmask=0077" "dmask=0077"];
  };

  swapDevices = [];

  nixpkgs.hostPlatform = lib.mkDefault "x86_64-linux";
  hardware.cpu.amd.updateMicrocode = lib.mkDefault config.hardware.enableRedistributableFirmware;
}
